---
# Config and command/sign-database for CommandShop by BoxOfDevs:

# Messages:

#   Coming in later update, stay tuned!

# List and database of buyable commands:

commands:
  example:
    cmd: "tp {player} 123 123 123"
    price:
      paytype: "item"
      item: "1:0:64"

# List and database for CommandShop signs:

signs:

...
